### ISSUE TITLE
Adding action methods in the <Menu /> component

### ISSUE THREAD

**Issue by Sebas3245** [selsa-inube/linpar#195]
Currently we have a new component called MenuLink which in turn delivers a list of another new component called MenuLink however as its name suggests this MenuLink currently only works for your options redirect to another section of the page, although this works for its main purpose for which it was created (to display the menu on mobile in the section to invite a new user)

![image](https://github.com/selsa-inube/linpar/assets/55991750/49f6b004-20c5-4f5b-a0b3-2a6e10fb571d)

There are other cases in which a Menu is required to display certain options but not specifically to redirect, for example the case of assigning/unassigning rows within the branch form in the "edit user" section:

![image](https://github.com/selsa-inube/linpar/assets/55991750/9592122f-56eb-4539-8d12-8a9ee317d00a)

This requires its options to trigger a certain function (which the current Menu component cannot do).

The relation between these two cases is that they both must show a menu that in terms of design is the same.

The following issue is to propose that this Menu component be updated either by changing the MenuLink so that depending on its properties it has the responsibility to "redirect" or trigger certain functions that pass between its list of options, however this would perhaps imply changing the name of MenuLink to something more related as MenuOption, the other option would be to create another component MenuOption a part from MenuLink and that the component MenuLink according to its properties decides which one should be called.

This could help us to implement a more general component for all the possible cases in mobile in which we require this menu of options

**Comment by wfercanas** [comment]
Vamos con la opción de crear otro componente, así tenemos uno para links y otro para acciones.
