### ISSUE TITLE
forms button styles are not working and error in the use of forms in responsive

### ISSUE THREAD

**Issue by novadeveloper14** [selsa-inube/linpar#210]
1. cuando se usan los botones de asignar y desasignar todo de los formularios estos no cambian de estilos como se muestra en los diseños:

storybook:

![image](https://github.com/selsa-inube/linpar/assets/87447257/a0038c89-f222-4ffe-84bb-da39f0bdc6a1)

diseño:

![image](https://github.com/selsa-inube/linpar/assets/87447257/589dc891-85b9-4412-981b-cf00a166a47e)

**Comment by wfercanas** [comment]
Ambos botones deben ser de appereance primary. Sin embargo, cada uno debe cambiar a disabled={true} si la acción que propone ya no tiene sentido (ej: asignar todo cuando todo ya ha sido asignado).
