### ISSUE TITLE
error in the responsive of the forms in the buttons when they are used in linpar

### ISSUE THREAD

**Issue by novadeveloper14** [selsa-inube/linpar#211]
cuando se utilizan los formularios en linpar y se manejan medidas de pantalla pequeñas los botones se dañan algo que no pasa en storybook.

![image](https://github.com/selsa-inube/linpar/assets/87447257/6fe71487-0934-4b26-93f7-3de4a83ad36f)

![image](https://github.com/selsa-inube/linpar/assets/87447257/7ce312d4-4339-414b-bfc9-7c09d4e247b5)

**Comment by Sebas3245** [comment]
Duplicate of #251
