### ISSUE TITLE
Controlar si se retorna un ícono u otro componente en las actions de una tabla

### ISSUE THREAD

**Issue by Sebas3245** [selsa-inube/linpar#219]
Actualmente tenemos acciones para las tablas de users y invitations, en el desarrollo surgió que estas acciones se independizaron en componentes aparte junto con sus responsabilidades con el fin de que el componente Table no tuviera que lidiar con el peso de controlar sus objetivos además de mostrarlas, por ende, esto nos da una manipulación corta de estos componentes de acción si lo vemos a través de otros componentes que declaren esas acciones a través de su propiedad "content", Ej:. 

InteractiveModal:
![image](https://github.com/selsa-inube/linpar/assets/55991750/a78cb5f3-8e76-40cd-988f-1fe9aab06c73)

Sucede que si bien las acciones pueden cumplir con su objetivo desde cualquier parte de la aplicación donde se llame su propiedad "content", no podemos tener acceso más allá a su presentación básica y actualmente en el InteractiveModal (como podría pasar en otros componentes) se requiere que estas acciones presenten una descripción a su derecha:

![image](https://github.com/selsa-inube/linpar/assets/55991750/109d708a-4d45-4cef-ac0f-c7b69b4aaa95)

Y si bien tenemos la propiedad "actionName" proveniente del objeto de acciones y podemos mostrarla, con solo esto el componente se quedaría corto en cuanto a UX ya que al presionar el nombre también debería ejecutar la acción, por lo tanto el presente issue es para solicitar un desarrollo en el cual estas acciones puedan o no tener un label para poder disparar la acción al hacer click en el texto y no solo al hacer click en el icono, así mismo añadir el comportamiento hover para cambiar el color del texto y el icono

**Comment by wfercanas** [comment]
Creo que más que tener un label o no, hay que controlar si la action retorna sólo el icon, si retorna un button y de qué tipo (error, success, ...), si devuelve un Switch con un label, etc..
Eso habría que hacerlo quizá dentro del componente DeleteUser, ActivateUser, etc.., con una prop que le hagamos llegar al interface.jsx
