### ISSUE TITLE
Convertir todos los breadcrumbs a español

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#254]
Actualmente tenemos configurados los textos a mostrar en los breadcrumbs en inglés. Ya que todo lo demás está quedando en español, es preferible dejar esto también en español.

**Comment by wfercanas** [comment]
Hay que arreglar primero los Breadcrumbs, porque por ahora sólo recibe la route

**Comment by cmarin001** [comment]
The resolution of this issue has been implemented and the fix is currently merged into the main branch.
