### ISSUE TITLE
El Nav no está ocupando el ancho correcto

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#327]
En el componente AppPage se está definiendo una grilla con 2 columnas. Estas están definidas como "auto 1fr". Lo que significa que este componente espera que el Nav defina el ancho.
Sin embargo, el Nav importado del design-system está usando un width de 100%, por lo que espera que sea quien lo usa quien defina el ancho usando al padre del Nav.

Creo que el ancho del Nav es algo que debería ser decisión del Nav mismo, ya que por dentro los navlinks y demás pueden obligar a la definición de un ancho determinado (conocimiento que no deberían tener todas las apps que usen el Nav). Por lo tanto, hay que gestionar ese ajuste con design-system.

**Comment by Sebas3245** [comment]
solved
