### ISSUE TITLE
Fix spacing between breadcrumbs and page title

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#457]
According to the mockups, this space should be s300, which means 24px in the tokens conversion. Currently the spacing is using 32px.
![image](https://github.com/selsa-inube/linpar/assets/36939686/bd7945b1-b6c2-4f90-ac67-18e861dce5ce)

**Comment by cmarin001** [comment]
The resolution of this issue has been implemented and the fix is currently merged into the main branch.
