### ISSUE TITLE
Fix padding of `<main />`

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#458]
We may have an element that renders its children as an outlet in the privileges process. Such element should be controlling the padding of the container where the content is rendered.

Find it a correct the use of tokens spacings, since according to the mockups the top and bottom paddings should be s400 --32px--, but the screen has 64px.

![image](https://github.com/selsa-inube/linpar/assets/36939686/e984ac1e-115e-4f30-b82f-65f72a49348a)

**Comment by cmarin001** [comment]
The issue has been resolved and the solution is currently deployed in the production environment.
