### ISSUE TITLE
Burger menu in header display should match the removal of the nav

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#459]
The screenshot is taken with a viewport at 1400px, the range in which the burger menu starts to be displayed. This behavior is incorrect:
1. The burger menu should be displayed when the nav is hidden. Both things should be in sync.
2. The burger menu is intended to work in the tablet/mobile range. 1400px is still way too wide to display the icon.

![image](https://github.com/selsa-inube/linpar/assets/36939686/2f57d86a-f06d-4026-8835-b5b2620b5925)

**Comment by cmarin001** [comment]
The issue has been resolved and the solution is currently deployed in the production environment.
