### ISSUE TITLE
Fix the width of main when in responsive

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#460]
The width of the main section of the app has problems defining its width. Once the nav is removed, the main section appears to have a max-width or something like that working, causing that the app is not using the whole width of the screen.

![image](https://github.com/selsa-inube/linpar/assets/36939686/f599dca7-7366-4417-853c-1ca470ee4f0e)

**Comment by cmarin001** [comment]
The issue has been resolved and the solution is currently deployed in the production environment.
