### ISSUE TITLE
Opening the tabs in select mode shouldn't move the whole content down

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#461]
If you open the tabs in select mode, the list should be displayed on top of the content. Right now the list is causing the whole content of the page to move down.
In this case the list is just two items long, but with a more extended list the movement would be considerable.

**Conclusion: opening the tab select shouldn't move the content.**

![image](https://github.com/selsa-inube/linpar/assets/36939686/48cfa98b-5092-465e-ab8a-25b2397f3d04)

**Comment by cmarin001** [comment]
The issue has been resolved and the solution is currently deployed in the production environment.
