### ISSUE TITLE
Fix cancel button in modals

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#463]
The buttons that is used for the cancel action in a modal according with the mockups is a filled button with gray appearance. The aesthetics of that type of button in the design-system indicates that such button has a gray background but no border.
As you can see, the button that is currently being displayed has a dark border, which isn't correct:

![image](https://github.com/selsa-inube/linpar/assets/36939686/f1563412-2abd-4e81-855b-b3b8999a2455)

**Comment by cmarin001** [comment]
The resolution of this issue has been implemented and the fix is currently merged into the main branch.
