### ISSUE TITLE
SectionMessage should appear on top of the content

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#464]
The SectionMessage appears to be following the flow of the document. When you activate a user and confirm your action, the SectionMessage is supposed to be displayed in the bottom-right corner of the screen, over the content of the page, but it is displayed below all the content.
This causes that the user scrolls down to be able to see it.

**Fix: the section message shouldn't flow with the document, it must be always visible in the area assigned when the app is reporting something to the user.**

![image](https://github.com/selsa-inube/linpar/assets/36939686/ba1462b5-b43f-420f-a5af-0c827bde1cd2)

**Comment by cmarin001** [comment]
The issue has been resolved and the solution is currently deployed in the production environment.
