### ISSUE TITLE
The validations of the inputs in invite user aren't working

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#469]
The form has two moments when the validations are run:
1. When the user finishes typing the content of the input and a blur event triggers when the user changes from one input to another.
2. When the user tries to send the form at the end.

**Problems**
1. Right now, when the user types a name, for example, the forms doesn't say a thing. If a name is valid, like "Rodrigo", the input should say that the input is correct. If a name is invalid, like "123", the input should warn the user.
2. When the form is submitted, the SectionMessage indicates that there are problems in some parts of the form, but the form doesn't display them.

![image](https://github.com/selsa-inube/linpar/assets/36939686/1f068b8a-0c8b-43d0-9a4f-78a9c9d7715c)

**Comment by cmarin001** [comment]
The issue has been resolved and the solution is currently deployed in the production environment.
