### ISSUE TITLE
Fix responsiveness of the process of editing a user

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#471]
The process isn't working properly in responsive:
1. The card of the currently modified user is broken.
2. The form for the general information step has two columns in desktop range, but when the inputs starts collapsing, the page should switch to a one column display.

![image](https://github.com/selsa-inube/linpar/assets/36939686/477b8983-c54d-4a13-b3f0-b4f35bdf02df)
![image](https://github.com/selsa-inube/linpar/assets/36939686/58634ee4-07e2-4c40-9859-f15c1a898e48)

**Comment by cmarin001** [comment]
The issue has been resolved and the solution is currently deployed in the production environment.
