### ISSUE TITLE
Fix layout in fieldset for assigning resources to a user

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#472]
This layout isn't properly aligned:
![image](https://github.com/selsa-inube/linpar/assets/36939686/105f2a36-7e7d-47f3-9a05-b430b7986e56)
![image](https://github.com/selsa-inube/linpar/assets/36939686/fbc0cfd8-e877-4941-9028-35622f79a41f)

**Comment by cmarin001** [comment]
The issue has been resolved and the solution is currently deployed in the production environment.
