### ISSUE TITLE
Fix layouts when assigning user resources in edit user process

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#473]
The buttons of cancel and save while editing a user should be right below the fieldset with the switches and resources. Nonetheless, the buttons are being displayed almost 50vh down.

Actually, you can completely see the buttons. You can only see a part of them.

![image](https://github.com/selsa-inube/linpar/assets/36939686/e71e567b-1ec0-48b3-8706-26ba98094dcc)

**Comment by cmarin001** [comment]
The issue has been resolved and the solution is currently deployed in the production environment.
