### ISSUE TITLE
Adjust spacing between buttons and inputs

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#517]
The spacing between the buttons and the inputs is greater in the mockups. Adjust using spacing tokens.
![image](https://github.com/selsa-inube/linpar/assets/36939686/d4702f6d-7c19-436a-9401-51498287444c)

**Note**: the parent of both the inputs and the buttons is a flex container. That container could use the spacing token in its gap property. There is no need in this case to create such spacing with a margin top in the button's container.

**Comment by cmarin001** [comment]
This issue was solved on SET572
