### ISSUE TITLE
Save and Cancel buttons should be disabled until a change is made in the palette

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#518]
If the user doesn't change any input value in the palette, the buttons to save and cancel should remain disabled. When the user makes a change, both buttons should become active.

So:
1. If the user doesn't change the initial state of the palette, both buttons are disabled.
2. If the user changes the value of one color, both buttons should become active so the user can decide if he/she wants to save or cancel changes.
3. If the user cancel changes, the values of all inputs return to the initial state of the palette and both buttons become disabled again because there are no changes compared with the initial state.
4. If the user saves changes, the values of the inputs are saved in state. After changing the state, this becomes the new baseline, so both buttons are now disabled again until the user makes a new change.
5. When the user gets to use both buttons, he/she remains in the current screen. There shouldn't be any navigation to other screen.

**Comment by cmarin001** [comment]
The matter has been successfully resolved under ticket PAR573.
