### ISSUE TITLE
Fieldsets are not using the whole with of the container, so buttons look misaligned

### ISSUE THREAD

**Issue by wfercanas** [selsa-inube/linpar#523]
The fieldsets for color text tokens should use the whole width so the screen looks aligned (justified). Right now that is not the case in wide desktop screens, making the layout look awkward:
![image](https://github.com/selsa-inube/linpar/assets/36939686/79aaf753-12ac-4953-8e4b-7a21c9cbb603)

The mockups looks like this:
![image](https://github.com/selsa-inube/linpar/assets/36939686/9158eec0-3c1e-48fe-8b9f-518c14100ab9)

**Comment by cmarin001** [comment]
this issue was solve on SET552
